### ISSUE TITLE
The setup for bundle adjustment is a bit unclear

### ISSUE THREAD

**Issue by astaranowicz** [idiap/multicamera-calibration#2]
Hi,
Great mini-library, I wanted to teach others using your code base.
After "perform the bundle adjustment" section, it seems to be unclear to me.
I have 3 cameras setup, lets say starting at 0 degrees, 45 degrees, and 90 degrees (quarter circle) facing inwards. I take 40 images between all of the cameras; some grid points can be seen by only 2 cameras at a time.

Using a checkerboard with a known grid, what annotations do I need to provide for build_ba.py? 
The input to build_ba.py along with the functions build_3d_points and write_ba_problem does not seem to be all that clear to me.

After performing the bundle adjustment, does extract_ba.py provide the transformations between each camera or all cameras to a single camera considered to be the origin?  What I am looking for is the transformations between cameras.

Thank you.

**Comment by SalimKayal** [comment]
The software was built with pedestrian recognition in mind.

The Idea of the annotations was to mark the heads and feets of pedestrian in the scene. any can be missing if they are seen on multiple cameras. Basically for your case I would put some objects with verticals on your calibration grid and annotate pixel wise the top and bottom of the object.

```
obj_id_1
0 bottom_in_px_x bottom_in_px_y
1 top_in_px_x top_in_px_y

...

obj_id_n
0 bottom_in_px_x bottom_in_px_y
1 top_in_px_x top_in_px_y
```
according to the same folder structure as everything else. the frame number being in sync between cameras.

then build_ba, bundle_adjuster, extract_ba

bundle_adjuster will move ALL the intrinsic and extrinsic values to match the best the annotations. If you require to have fixed points (the origin of the grid remains the same or something like that), you have to add them to the annotations using the -f option in build_ba.

projecting from a camera to an other one cannot be done as the 3d data is missing. you can project from a camera to a range of values in an other one or from at least two cameras to a single point in the third. look at the code in check_3d to see how it's done.

**Comment by astaranowicz** [comment]
Thank you for the reply.  The annotation part really helped.

From what I understood in the code, is that when i calibrate a single camera, I receive the intrinsics (camera matrix and distortions), but also the extrinsics (rotation and translation in meters) for every panel.  I thought the bundle adjustment takes in to account these positions (as performed by build_ba), and puts them all in a single reference frame.

Then I thought the extract_ba pulled those inter-camera extrinsics.  Once I had those estimated parameters, I could perform triangulation such as (https://github.com/ahmaurya/3d-reconstruction-visualization/blob/master/matlab/triangulate.m)  where all you need is 2 corresponding pixel points along with the intrinsics and extrinsics to scale.  Is extract_ba not pull the intercamera extrinsics. If not, what do you suggest I change to ensure I can?

Best

**Comment by SalimKayal** [comment]
The adjusted extrinsics will also be extracted by extract_ba. Once you have all that, you can indeed calculate a 3d point in the scene from two points in different cameras and then project this point on any of the others (see build_3d_point, solve_projections and refresh in scripts/check_3d.py)
