### ISSUE TITLE
Running the build_ba

### ISSUE THREAD

**Issue by dawei-NingGu** [idiap/multicamera-calibration#6]
Hi,
l'm learning your code.
I need a .pos file to launch the build_ba script,but I don't understand the instructions of the file.Can you tell me what this file is?What is 'feet'?What is 'head'?

**Comment by SalimKayal** [comment]
the head/feet is for legacy reasons, this soft was developed originally for pedestrian detection, hence head of the pedestrian, feet of the pedestrian. In your use case you may use any vertical line.

the pos file is basically a list of 

```
ID_0
point_id x y
point_id x y

ID_1
point_id x y
point_id x y

...

ID_n
point_id x y
point_id x y
```

**Comment by dawei-NingGu** [comment]
Thanks for your response, that was very helpful to me
