### ISSUE TITLE
How to run the extrinsic calibration

### ISSUE THREAD

**Issue by ghPak1002** [idiap/multicamera-calibration#8]
When I execute the extrinsic calibration, I click the point and the question that request the x coordinate appears. I then input an integer, but Nothing happens...

How could I run the extrinsic calibration?

**Comment by SalimKayal** [comment]
* you click a point
* you input the x coordinate as a float in cm
* you press enter
* you input the y coordinate as a float in cm
* you press enter
* when you have enough points  you press s to save

**Comment by ghPak1002** [comment]
For example, I type the x coordinate as 1.22 and press enter, the process doesn't continue... the interface only shows the same question.
